---
- name: install denpendency package
  yum: name={{ item }} state=present
  with_items:
    - pcre
    - openssl
    - pcre-devel
    - openssl-devel
    - zlib-devel
    - gd
    - gd-devel

- name: create nginx pid user
  user: name={{ nginxuser }} system=yes shell=/sbin/nologin createhome=no

- name: compile and install nginx
  shell: > 
    tar xf {{ srcpath }}/{{ nginxtar }} -C {{ srcpath }} && \ 
    cd {{ srcpath }}/{{ nginxtar | replace('.tar.gz','')}} && \
    ./configure --prefix={{ nginxpath }} \
    --user={{ nginxuser }} --group={{ nginxgroup }} \
    --with-http_ssl_module \
    --with-http_realip_module \
    --with-http_image_filter_module \
    --with-http_mp4_module \
    --with-http_flv_module \
    --with-http_gzip_static_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-pcre \
    --with-http_stub_status_module && \
    make -j `lscpu | awk '$1~/^CPU\(s\):/{print $2}'` && \
    make install
  args:
    creates: "{{ nginxpath }}"
     
- name: copy nginx systemd script
  template: src=nginx.systemd dest=/lib/systemd/system/nginx.service
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  notify: start nginx service

- name: copy nginx init script
  template: src=nginx.init dest=/etc/init.d/nginx
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  notify: start nginx service

